### ISSUE TITLE
Phone app: date change doesnt save correctly

### ISSUE THREAD

**Issue by MiriamNZ** [actualbudget/releases#248] opened 2022-04-08 03:37 UTC
I go into a transaction,
I edit the date field. 
I save. 
The date change is not saved. 

I go into a transaction,
I edit the date field. 
I click into the notes field
I save. 
The date change is saved. 

I shouldn't need to click into a different field to make the new date stick.

Iphone. IOS 15.4.1

**Comment by Kidglove57** [comment] 2022-04-08 06:45
I have just tried this on an iPhone OS 15 and the date change sticks after I press save. I do not have to go into any other field.

So I am wondering why our experiences should be so different?

**Comment by ghost** [comment] 2022-04-08 13:12
Perhaps it is a question of your date formatting. Due to how actual is written, you currently have to write out the full date for the app to register it as correct date. So depending on your location it would be mm.dd.yyyy or dd.mm.yyyy.
This might also be the cause for your other issue #247  ?

**Comment by Deguello** [comment] 2022-04-08 14:25
All the more reason this should be using a date picker widget, imo.

**Comment by rich-howell** [comment] 2022-10-16 19:14
Hey @MiriamNZ 

I am sorry for the late reply, the apps are no longer supported, Actual self hosted is now moving to a responsive web app in place of the mobile applications.

Cheers
Rich

**Closed as completed by rich-howell** 2022-10-16 19:14 UTC
