### ISSUE TITLE
scheduled transaction remains selected after skipping.

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/releases#63] opened 2021-11-16 02:23 UTC
I had a scheduled transaction of a CC payment that I didn't need to pay this month, so I selected it, and chose "Skip scheduled date" to make it disappear from my list of upcoming transactions.  But after I had done that, and then selected another transaction, the header said "2 transactions" were selected.  After I deselected the one transaction, it still shows that one is selected (the checkbox on the header to the left of "date" is selected, and the link to the left of the "Collapse split transactions" icon indicates "1 transactions".

I have to deselect the "select all" checkbox before I can continue on.

**Comment by Silvenga** [comment] 2021-11-16 16:05
This appears to be the case if you skip or post the transaction.

**Comment by MikeBishop** [comment] 2021-11-16 17:05
It's less bad when it's something that's actually on the screen.  Skipping a transaction, having it no longer in the list, but still be selected is pure bug -- keeping the newly posted transaction selected is a UI preference.

**Comment by Silvenga** [comment] 2021-11-16 18:29
No, the new transaction isn't selected, but the old row is still checked (now hidden?). 

EDIT: Example:

![image](https://user-images.githubusercontent.com/2753330/142047756-4de9dc33-67e8-458a-8025-d112f11080e9.png)

In this case, I posted Github. Note that something is still checked (the context menu suggests that it's the scheduled payment row), while the new transaction isn't checked.

**Comment by bpaulien** [comment] 2022-02-14 18:22
cross posting this with the bug that's been fixed.

https://github.com/actualbudget/releases/issues/199#issue-1132885478

**Comment by jlongster** [comment] 2022-02-14 18:33
Thanks a lot! Yes this will be fixed in #199. Closing this because that's the bug that is being tracked with the release notes.

(I have confirmed that the fix also works with interactions with scheduled transactions)

**Closed as completed by jlongster** 2022-02-14 18:33 UTC
