### ISSUE TITLE
Split transactions not taken into account when viewing category transactions

### ISSUE THREAD

**Issue by alehel** [actualbudget/releases#176] opened 2022-01-13 08:01 UTC
If I click on a category to see its transactions, it seems like those that are part of split transactions are not being taken into account in the total. Below are two examples.

![image](https://user-images.githubusercontent.com/22277624/149289482-e3fbdf3e-55c1-4847-86a4-6da76f72c322.png)
Here there are 3 transactions in the relevant category. However, the total only seems to be calculated based on the two transactions which are not part of a split transaction. The actual cleared total should be 1743.4.

![image](https://user-images.githubusercontent.com/22277624/149289310-5a07c253-55b3-433a-8f6f-44331097ca8b.png)
Here there are 2 transaction in the relevant category. The total is, again, missing the split transaction. Cleared total should be 598.84.

Apologies if I've misunderstood something about the view :).

**Comment by Deguello** [comment] 2022-01-13 13:57
Yeah, that's what it's doing.
<img width="533" alt="Screen Shot 2022-01-13 at 7 56 06 AM" src="https://user-images.githubusercontent.com/16468471/149343287-f8ef0e6d-b882-412e-a1f8-d26702edfe12.png">

**Comment by ellemwano** [comment] 2022-02-27 09:23
I believe this is a duplicate of issue #127

**Closed as completed** 2022-03-12 16:44 UTC
Labels: fixed, 0.0.147

**Comment by mkemen** [comment] 2022-03-13 10:03
Strange.  This seems to be working in all but one category.   I have checked all categories from March and February that contain split items and they are all adding up correctly on this "sub-report".   All but one that is.   There is one category in February that continues to not count the split amount in the report.

**Comment by mkemen** [comment] 2022-03-13 10:17
This seems to be related to one transaction.  If I delete the transaction, the sub-report still remains wrong by the amount of the transaction I deleted.

**Comment by mkemen** [comment] 2022-03-13 10:23
![Screenshot 2022-03-13 061936](https://user-images.githubusercontent.com/94459902/158055138-ac0f596b-8790-4692-80ed-bad0e0afabe0.jpg)
![Screenshot 2022-03-13 062059](https://user-images.githubusercontent.com/94459902/158055140-8cb85065-44db-4325-a62b-4b5a0298e0ed.jpg)
![Screenshot 2022-03-13 062144](https://user-images.githubusercontent.com/94459902/158055144-6245710c-868e-4962-84b5-26d4dc1a95ae.jpg)
![Screenshot 2022-03-13 062210](https://user-images.githubusercontent.com/94459902/158055145-400ee831-ed88-4052-93e7-327896120eba.jpg)
