### ISSUE TITLE
Category totals do not include split transactions when clicking activity on budget screen

### ISSUE THREAD

**Issue by jakubasgard** [actualbudget/releases#226] opened 2022-03-04 23:07 UTC
On budget screen, where I see all activity for given month, I can click the amount to easily see all transactions within that month/category. However, the totals on top of the screen are wrong, because they do not include amounts from split transactions...

**Comment by Deguello** [comment] 2022-03-05 12:40
https://github.com/actualbudget/releases/issues/176

**Comment by jlongster** [comment] 2022-03-05 16:25
Thanks @Deguello, yes this looks like a dupe of https://github.com/actualbudget/releases/issues/176. I remember looking into this but it got lost, so thanks for bringing it up again. I'll tag it in the next release (the other issue) to make sure it gets fixed

**Closed as completed by jlongster** 2022-03-05 16:25 UTC
